apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "urule.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "urule.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "urule.fullname" . }}
    spec:
      containers:
        - name: {{ include "urule.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: COUNTRY
              value: "{{ .Values.env.COUNTRY }}"
            - name: TIMEZONE
              value: "{{ .Values.env.TIMEZONE }}"
            - name: PROFILE
              value: "{{ .Values.env.PROFILE }}"
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: RUN_ARGS
              value: "{{ .Values.env.RUN_ARGS }}"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 30
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
