namespace: ghana

replicaCount: 1

image:
  repository: harbor.bjxsre.com/bjx-ghana-test/urule
  tag: 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2012

ingress:
  enabled: true
  hostname: k8s-urule-ghana.bjxsre.com
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: bjx-eks-hk-tools
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-east-1:398250236375:certificate/a02a1783-2918-4cdd-85c6-ec9ffd6a2ae4
    alb.ingress.kubernetes.io/security-groups: sg-0f5bf935f9d3f339f
    alb.ingress.kubernetes.io/group.name: common

env:
  COUNTRY: ghana
  TIMEZONE: Africa/Accra
  PROFILE: dev
  JAVA_OPTS: "-Duser.timezone=Africa/Accra"
  RUN_ARGS: "--spring.config.location=classpath:/ghana/ --spring.profiles.active=dev"

imagePullSecrets:
  - name: harbor-secret

harbor:
  registry: harbor.bjxsre.com
  username: admin
  password: Harbor12345
