{{- define "imagePullSecret" }}
{{- $auth := printf "%s:%s" .Values.harbor.username .Values.harbor.password | b64enc }}
{{- $authJson := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.harbor.registry .Values.harbor.username .Values.harbor.password $auth }}
{{- $authJson | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

